// @ts-check
/**
 * src/copilot/events/nerv-events.js
 *
 * FAIXA-L3 — Mapeamento bidirecional EventBus ↔ NERV actionCodes.
 *
 * Centraliza a correspondência entre event types do EventBus (SSOT) e os
 * actionCodes usados pelo NERV bus externo.
 *
 * O NervEventBusAdapter consome este módulo para relay EventBus → NERV (outbound)
 * e NERV → EventBus (inbound).
 *
 * @module copilot/events/nerv-events
 * @see bridges/nerv-event-bus-adapter.js
 */

import {
    AGENT_ABORT,
    AGENT_ASSISTANT_INTENT,
    AGENT_ASSISTANT_REASONING_COMPLETE,
    AGENT_ASSISTANT_TURN_END,
    AGENT_ASSISTANT_TURN_START,
    AGENT_BACKGROUND_COMPLETED,
    AGENT_BACKGROUND_IDLE,
    AGENT_BEFORE_STOP,
    AGENT_CONTEXT_COMPACTED,
    AGENT_DIALOG_BOOT_RECOVERY,
    AGENT_DIALOG_COMPACTION_REQUESTED,
    AGENT_DIALOG_DELTA,
    AGENT_DIALOG_LOOP_CHANGED,
    AGENT_DIALOG_PAUSED,
    AGENT_DIALOG_READY,
    AGENT_DIALOG_REPLY,
    AGENT_DIALOG_RESUMED,
    AGENT_DIALOG_STALLED,
    AGENT_DIALOG_STOPPED,
    AGENT_DIALOG_TURN_END,
    AGENT_DIALOG_TURN_START,
    AGENT_DIALOG_TURN_TIMEOUT,
    AGENT_ELICITATION_PENDING,
    AGENT_ERROR,
    AGENT_HANDOFF_ACCEPTED,
    AGENT_HANDOFF_RECEIVED,
    AGENT_HANDOFF_REJECTED,
    AGENT_MCP_RECONNECTED,
    AGENT_METRICS,
    AGENT_PERMISSION_MODE_CHANGED,
    AGENT_PR_CONSUMED,
    AGENT_PR_FALLBACK_MODEL,
    AGENT_QUESTION_ANSWERED,
    AGENT_QUESTION_PENDING,
    AGENT_QUOTA_WARNING,
    AGENT_READY,
    AGENT_SDK_LIFECYCLE,
    AGENT_SESSION_CLEANUP,
    AGENT_SESSION_COMPACTION_COMPLETE,
    AGENT_SESSION_COMPACTION_START,
    AGENT_SESSION_CONTEXT_CHANGED,
    AGENT_SESSION_ERROR,
    AGENT_SESSION_FATAL,
    AGENT_SESSION_HANDOFF,
    AGENT_SESSION_HISTORY_SYNCED,
    AGENT_SESSION_INFO,
    AGENT_SESSION_KEEPALIVE,
    AGENT_SESSION_MODE_CHANGED,
    AGENT_SESSION_SHUTDOWN,
    AGENT_SESSION_SNAPSHOT_REWIND,
    AGENT_SESSION_TASK_COMPLETE,
    AGENT_SESSION_TITLE_CHANGED,
    AGENT_SESSION_TOKEN_BUDGET_WARNING,
    AGENT_SESSION_TRUNCATION,
    AGENT_SESSION_USAGE,
    AGENT_SESSION_WORKSPACE_FILE_CHANGED,
    AGENT_SHELL_COMPLETED,
    AGENT_SHELL_DETACHED_COMPLETED,
    AGENT_SHUTDOWN,
    AGENT_STEERING_SENT,
    AGENT_STOPPED,
    AGENT_SUBAGENT_COMPLETED,
    AGENT_SUBAGENT_FAILED,
    AGENT_SUBAGENT_STARTED,
    AGENT_SYSTEM_MESSAGE,
    AGENT_TASK_COMPLETED,
    AGENT_TASK_DELTA,
    AGENT_TASK_ERROR,
    AGENT_TASK_QUEUED,
    AGENT_TASK_REASONING,
    AGENT_TASK_STARTED,
    AGENT_TOOL_EXECUTION_COMPLETE,
    AGENT_TOOL_EXECUTION_PROGRESS,
    AGENT_TOOL_EXECUTION_START,
} from './agent-events.js';
import {
    HOOK_ERROR_OCCURRED,
    HOOK_POST_TOOL_USE,
    HOOK_PRE_TOOL_USE,
    HOOK_PROMPT_SUBMITTED,
    HOOK_SESSION_END,
    HOOK_SESSION_START,
} from './hook-events.js';
import {
    HUB_ERROR,
    HUB_SESSION_CLOSED,
    HUB_SESSION_CREATED,
    HUB_TURN_COMPLETE,
    HUB_TURN_SENT,
    HUB_USER_INJECTED,
} from './hub-events.js';
import {
    CONFIG_PINNED_FILES_CHANGED,
    HEALTH_DEGRADED,
    HEALTH_RECOVERED,
    SYSTEM_SHUTDOWN_COMPLETE,
    SYSTEM_SHUTDOWN_STARTED,
} from './system-events.js';

// ── Outbound: EventBus type → NERV actionCode ───────────────────────────────

/**
 * Mapa de EventBus event types → NERV actionCodes para relay outbound.
 * O NervEventBusAdapter subscreve estes tipos e os encaminha ao NERV.
 *
 * @type {Readonly<Record<string, string>>}
 */
export const EVENTBUS_TO_NERV = Object.freeze({
    // Agent lifecycle
    [AGENT_READY]: 'COPILOT_AGENT_READY',
    [AGENT_BEFORE_STOP]: 'COPILOT_AGENT_BEFORE_STOP',
    [AGENT_STOPPED]: 'COPILOT_SESSION_STOPPED',
    [AGENT_SHUTDOWN]: 'COPILOT_AGENT_SHUTDOWN',
    [AGENT_ERROR]: 'COPILOT_AGENT_ERROR',
    [AGENT_METRICS]: 'COPILOT_AGENT_METRICS',

    // Agent session (full)
    [AGENT_SESSION_KEEPALIVE]: 'COPILOT_SESSION_KEEPALIVE',
    [AGENT_SESSION_FATAL]: 'COPILOT_SESSION_FATAL',
    [AGENT_SESSION_COMPACTION_START]: 'COPILOT_SESSION_COMPACTION_START',
    [AGENT_SESSION_COMPACTION_COMPLETE]: 'COPILOT_SESSION_COMPACTION_COMPLETE',
    [AGENT_SESSION_USAGE]: 'COPILOT_SESSION_USAGE',
    [AGENT_SESSION_TOKEN_BUDGET_WARNING]: 'COPILOT_SESSION_TOKEN_BUDGET_WARNING',
    [AGENT_SESSION_MODE_CHANGED]: 'COPILOT_SESSION_MODE_CHANGED',
    [AGENT_SESSION_HISTORY_SYNCED]: 'COPILOT_SESSION_HISTORY_SYNCED',
    [AGENT_SESSION_INFO]: 'COPILOT_SESSION_INFO',
    [AGENT_SESSION_TITLE_CHANGED]: 'COPILOT_SESSION_TITLE_CHANGED',
    [AGENT_SESSION_SNAPSHOT_REWIND]: 'COPILOT_SESSION_SNAPSHOT_REWIND',
    [AGENT_SESSION_WORKSPACE_FILE_CHANGED]: 'COPILOT_SESSION_WORKSPACE_FILE_CHANGED',

    // Agent tasks (full)
    [AGENT_TASK_QUEUED]: 'COPILOT_TASK_QUEUED',
    [AGENT_TASK_STARTED]: 'COPILOT_TASK_STARTED',
    [AGENT_TASK_COMPLETED]: 'COPILOT_TASK_COMPLETED',
    [AGENT_TASK_DELTA]: 'COPILOT_TASK_DELTA',
    [AGENT_TASK_ERROR]: 'COPILOT_TASK_ERROR',
    [AGENT_TASK_REASONING]: 'COPILOT_TASK_REASONING',

    // Dialog events (full)
    [AGENT_DIALOG_READY]: 'COPILOT_DIALOG_READY',
    [AGENT_DIALOG_LOOP_CHANGED]: 'COPILOT_DIALOG_LOOP_CHANGED',
    [AGENT_DIALOG_TURN_START]: 'COPILOT_TURN_START',
    [AGENT_DIALOG_TURN_END]: 'COPILOT_TURN_END',
    [AGENT_DIALOG_STALLED]: 'COPILOT_DIALOG_STALLED',
    [AGENT_DIALOG_TURN_TIMEOUT]: 'COPILOT_TURN_TIMEOUT',
    [AGENT_DIALOG_PAUSED]: 'COPILOT_DIALOG_PAUSED',
    [AGENT_DIALOG_RESUMED]: 'COPILOT_DIALOG_RESUMED',
    [AGENT_DIALOG_STOPPED]: 'COPILOT_DIALOG_STOPPED',
    [AGENT_DIALOG_REPLY]: 'COPILOT_DIALOG_REPLY',
    [AGENT_DIALOG_COMPACTION_REQUESTED]: 'COPILOT_COMPACTION_PROACTIVE_REQUEST',

    // Tool events
    [AGENT_TOOL_EXECUTION_START]: 'COPILOT_TOOL_EXECUTION_START',
    [AGENT_TOOL_EXECUTION_COMPLETE]: 'COPILOT_TOOL_EXECUTION_COMPLETE',
    [AGENT_TOOL_EXECUTION_PROGRESS]: 'COPILOT_TOOL_EXECUTION_PROGRESS',

    // Question/permission
    [AGENT_QUESTION_PENDING]: 'COPILOT_QUESTION_PENDING',
    [AGENT_QUESTION_ANSWERED]: 'COPILOT_QUESTION_ANSWERED',
    [AGENT_PERMISSION_MODE_CHANGED]: 'COPILOT_PERMISSION_MODE_CHANGED',
    [AGENT_PR_CONSUMED]: 'COPILOT_PR_CONSUMED',
    [AGENT_PR_FALLBACK_MODEL]: 'COPILOT_PR_FALLBACK_MODEL',

    // Context/misc
    [AGENT_CONTEXT_COMPACTED]: 'COPILOT_CONTEXT_COMPACTED',
    [AGENT_SYSTEM_MESSAGE]: 'COPILOT_SYSTEM_MESSAGE',

    // Handoff events
    [AGENT_HANDOFF_RECEIVED]: 'COPILOT_HANDOFF_RECEIVED',
    [AGENT_HANDOFF_ACCEPTED]: 'COPILOT_HANDOFF_ACCEPTED',
    [AGENT_HANDOFF_REJECTED]: 'COPILOT_HANDOFF_REJECTED',

    // FAIXA-L9: Assistant events (previously unbridged)
    [AGENT_ASSISTANT_TURN_START]: 'COPILOT_ASSISTANT_TURN_START',
    [AGENT_ASSISTANT_TURN_END]: 'COPILOT_ASSISTANT_TURN_END',
    [AGENT_ASSISTANT_INTENT]: 'COPILOT_ASSISTANT_INTENT',
    [AGENT_ASSISTANT_REASONING_COMPLETE]: 'COPILOT_ASSISTANT_REASONING_COMPLETE',

    // FAIXA-L9: Session events (previously unbridged)
    [AGENT_SESSION_ERROR]: 'COPILOT_SESSION_ERROR',
    [AGENT_SESSION_SHUTDOWN]: 'COPILOT_SESSION_SHUTDOWN',
    [AGENT_SESSION_HANDOFF]: 'COPILOT_SESSION_HANDOFF',
    [AGENT_SESSION_TASK_COMPLETE]: 'COPILOT_SESSION_TASK_COMPLETE',
    [AGENT_SESSION_CONTEXT_CHANGED]: 'COPILOT_SESSION_CONTEXT_CHANGED',
    [AGENT_SESSION_TRUNCATION]: 'COPILOT_SESSION_TRUNCATION',
    [AGENT_SESSION_CLEANUP]: 'COPILOT_SESSION_CLEANUP',

    // FAIXA-L9: Subagent events
    [AGENT_SUBAGENT_STARTED]: 'COPILOT_SUBAGENT_STARTED',
    [AGENT_SUBAGENT_COMPLETED]: 'COPILOT_SUBAGENT_COMPLETED',
    [AGENT_SUBAGENT_FAILED]: 'COPILOT_SUBAGENT_FAILED',

    // FAIXA-L9: Dialog events (previously unbridged)
    [AGENT_DIALOG_DELTA]: 'COPILOT_DIALOG_DELTA',
    [AGENT_DIALOG_BOOT_RECOVERY]: 'COPILOT_DIALOG_BOOT_RECOVERY',

    // FAIXA-L9: Abort / Elicitation
    [AGENT_ABORT]: 'COPILOT_ABORT',
    [AGENT_ELICITATION_PENDING]: 'COPILOT_ELICITATION_PENDING',

    // FAIXA-L9: Background / Shell
    [AGENT_BACKGROUND_COMPLETED]: 'COPILOT_AGENT_BACKGROUND_COMPLETED',
    [AGENT_BACKGROUND_IDLE]: 'COPILOT_AGENT_BACKGROUND_IDLE',
    [AGENT_SHELL_COMPLETED]: 'COPILOT_SHELL_COMPLETED',
    [AGENT_SHELL_DETACHED_COMPLETED]: 'COPILOT_SHELL_DETACHED_COMPLETED',

    // FAIXA-L9: Infra / Misc
    [AGENT_SDK_LIFECYCLE]: 'COPILOT_SDK_LIFECYCLE',
    [AGENT_MCP_RECONNECTED]: 'COPILOT_MCP_RECONNECTED',
    [AGENT_QUOTA_WARNING]: 'COPILOT_QUOTA_WARNING',
    [AGENT_STEERING_SENT]: 'COPILOT_STEERING_SENT',

    // Hub events
    [HUB_SESSION_CREATED]: 'COPILOT_HUB_SESSION_CREATED',
    [HUB_SESSION_CLOSED]: 'COPILOT_HUB_SESSION_CLOSED',
    [HUB_TURN_SENT]: 'COPILOT_HUB_TURN_SENT',
    [HUB_TURN_COMPLETE]: 'COPILOT_HUB_TURN_COMPLETE',
    [HUB_USER_INJECTED]: 'COPILOT_HUB_USER_INJECTED',
    [HUB_ERROR]: 'COPILOT_HUB_ERROR',

    // Hook events
    [HOOK_PRE_TOOL_USE]: 'COPILOT_HOOK_PRE_TOOL_USE',
    [HOOK_POST_TOOL_USE]: 'COPILOT_HOOK_POST_TOOL_USE',
    [HOOK_PROMPT_SUBMITTED]: 'COPILOT_HOOK_PROMPT_SUBMITTED',
    [HOOK_SESSION_START]: 'COPILOT_HOOK_SESSION_START',
    [HOOK_SESSION_END]: 'COPILOT_HOOK_SESSION_END',
    [HOOK_ERROR_OCCURRED]: 'COPILOT_HOOK_ERROR_OCCURRED',

    // System/config events
    [CONFIG_PINNED_FILES_CHANGED]: 'COPILOT_CONFIG_CHANGED',
    [HEALTH_DEGRADED]: 'COPILOT_HEALTH_DEGRADED',
    [HEALTH_RECOVERED]: 'COPILOT_HEALTH_RECOVERED',
    [SYSTEM_SHUTDOWN_STARTED]: 'COPILOT_SHUTDOWN_STARTED',
    [SYSTEM_SHUTDOWN_COMPLETE]: 'COPILOT_SHUTDOWN_COMPLETE',
});

// ── Inbound: NERV commands → EventBus ────────────────────────────────────────

/** @type {string} */ export const NERV_COMMAND_RECEIVED = 'nerv:command:received';
/** @type {string} */ export const NERV_COMMAND_SEND_MESSAGE = 'nerv:command:send_message';
/** @type {string} */ export const NERV_COMMAND_PAUSE = 'nerv:command:pause';
/** @type {string} */ export const NERV_COMMAND_RESUME = 'nerv:command:resume';
/** @type {string} */ export const NERV_COMMAND_RESTART = 'nerv:command:restart';

/**
 * Mapa de inbound command strings → EventBus types.
 *
 * @type {Readonly<Record<string, string>>}
 */
export const NERV_COMMAND_TO_EVENTBUS = Object.freeze({
    sendMessage: NERV_COMMAND_SEND_MESSAGE,
    pause: NERV_COMMAND_PAUSE,
    resume: NERV_COMMAND_RESUME,
    restart: NERV_COMMAND_RESTART,
});
