// src/shared/nerv/constants_v2.js

const ActionCodeV2 = {
  // ... existing action codes ...

  // Orchestration events
  ORCHESTRATION_STARTED: 'ORCHESTRATION_STARTED',
  ORCHESTRATION_COMPLETED: 'ORCHESTRATION_COMPLETED',
  ORCHESTRATION_FAILED: 'ORCHESTRATION_FAILED',
  ORCHESTRATION_PAUSED: 'ORCHESTRATION_PAUSED',
  ORCHESTRATION_RESUMED: 'ORCHESTRATION_RESUMED',

  // Workflow events
  WORKFLOW_STEP_STARTED: 'WORKFLOW_STEP_STARTED',
  WORKFLOW_STEP_COMPLETED: 'WORKFLOW_STEP_COMPLETED',
  WORKFLOW_STEP_FAILED: 'WORKFLOW_STEP_FAILED',
  WORKFLOW_STEP_SKIPPED: 'WORKFLOW_STEP_SKIPPED',
  SUBTASK_SPAWNED: 'SUBTASK_SPAWNED',
  SUBTASK_COMPLETED: 'SUBTASK_COMPLETED',

  // Iteration events
  ITERATION_STARTED: 'ITERATION_STARTED',
  ITERATION_COMPLETED: 'ITERATION_COMPLETED',
  ITERATION_CONVERGED: 'ITERATION_CONVERGED',
  ITERATION_DIVERGED: 'ITERATION_DIVERGED',

  // Validation events
  VALIDATION_STARTED: 'VALIDATION_STARTED',
  VALIDATION_COMPLETED: 'VALIDATION_COMPLETED',
  VALIDATION_PASSED: 'VALIDATION_PASSED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Quality events
  QUALITY_ASSESSED: 'QUALITY_ASSESSED',
  QUALITY_THRESHOLD_MET: 'QUALITY_THRESHOLD_MET',
  QUALITY_THRESHOLD_MISSED: 'QUALITY_THRESHOLD_MISSED',
  QUALITY_IMPROVED: 'QUALITY_IMPROVED',
  QUALITY_DEGRADED: 'QUALITY_DEGRADED',

  // Context events
  CONTEXT_INJECTED: 'CONTEXT_INJECTED',
  CONTEXT_CHUNKED: 'CONTEXT_CHUNKED',
  CONTEXT_SUMMARIZED: 'CONTEXT_SUMMARIZED',
  MEMORY_STORED: 'MEMORY_STORED',
  MEMORY_RETRIEVED: 'MEMORY_RETRIEVED',

  // Cost events
  TOKEN_USAGE_RECORDED: 'TOKEN_USAGE_RECORDED',
  COST_CALCULATED: 'COST_CALCULATED',
  BUDGET_WARNING: 'BUDGET_WARNING',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',

  // Progress events
  PROGRESS_MILESTONE: 'PROGRESS_MILESTONE',      // e.g., "Chapter 5/15 completed"
  PROGRESS_ESTIMATE_UPDATED: 'PROGRESS_ESTIMATE_UPDATED',
  TIME_REMAINING_UPDATED: 'TIME_REMAINING_UPDATED',

  // Driver events
  DRIVER_SELECTED: 'DRIVER_SELECTED',
  DRIVER_FALLBACK: 'DRIVER_FALLBACK',
  DRIVER_CAPABILITY_CHECK: 'DRIVER_CAPABILITY_CHECK',

  // Self-correction events
  SELF_CORRECTION_INITIATED: 'SELF_CORRECTION_INITIATED',
  SELF_CORRECTION_COMPLETED: 'SELF_CORRECTION_COMPLETED',
  ERROR_ANALYZED: 'ERROR_ANALYZED',
  FIX_APPLIED: 'FIX_APPLIED'
};
