// @ts-check
/**
 * Canonical BYOK/model routing domain.
 *
 * This barrel intentionally exposes only stable contracts and projections. Runtime bridges should depend on this module,
 * while `src/copilot/sdk` remains the thin GitHub Copilot SDK boundary.
 *
 * @module copilot/model-gateway
 */

export {
    MODEL_GATEWAY_CATALOG_CONFIDENCE,
    MODEL_GATEWAY_CATALOG_SCHEMA_VERSION,
    MODEL_GATEWAY_SQLITE_SCHEMA_SQL,
    MODEL_GATEWAY_SQLITE_SCHEMA_VERSION,
    MODEL_GATEWAY_SQLITE_TABLES,
    ANTHROPIC_MODELS_API_VERSION,
    ANTHROPIC_MODELS_CATALOG_URL,
    CEREBRAS_PUBLIC_MODELS_CATALOG_URL,
    CHUTES_MODELS_CATALOG_URL,
    CHUTES_OPENAI_BASE_URL,
    CLOUDFLARE_AI_GATEWAY_UNIVERSAL_URL,
    CLOUDFLARE_WORKERS_AI_MODELS_CATALOG_URL,
    CLOUDFLARE_WORKERS_AI_OPENAI_BASE_URL,
    CLOUDFLARE_WORKERS_AI_REST_BASE_URL,
    DEFAULT_MODEL_GATEWAY_CATALOG_PATH,
    GEMINI_MODELS_API_VERSION,
    GEMINI_MODELS_CATALOG_URL,
    GEMINI_OPENAI_COMPATIBLE_BASE_URL,
    GROQ_DOCS_MODELS_URL,
    GROQ_MODELS_CATALOG_URL,
    GROQ_OPENAI_BASE_URL,
    GROQ_PRICING_URL,
    HUGGINGFACE_ROUTE_POLICY_SUFFIXES,
    HUGGINGFACE_ROUTER_BASE_URL,
    HUGGINGFACE_ROUTER_MODELS_URL,
    KILO_GATEWAY_MODELS_CATALOG_URL,
    KILO_GATEWAY_PROVIDERS_CATALOG_URL,
    MISTRAL_MODELS_CATALOG_URL,
    NVIDIA_NIM_BASE_URL,
    NVIDIA_NIM_MANAGEMENT_ENDPOINTS,
    NVIDIA_NIM_MODELS_CATALOG_URL,
    OLLAMA_LOCAL_API_BASE_URL,
    OLLAMA_LOCAL_OPENAI_BASE_URL,
    OLLAMA_LOCAL_SHOW_URL,
    OLLAMA_LOCAL_TAGS_URL,
    OPENCODE_ZEN_BASE_URL,
    OPENCODE_ZEN_CHAT_COMPLETIONS_URL,
    OPENCODE_ZEN_DOCS_URL,
    OPENCODE_ZEN_MESSAGES_URL,
    OPENCODE_ZEN_MODELS_URL,
    OPENCODE_ZEN_RESPONSES_URL,
    OPENAI_MODEL_LIST_OBJECT,
    OPENAI_MODEL_OBJECT,
    OPENAI_MODELS_CATALOG_URL,
    OPENROUTER_MODELS_CATALOG_URL,
    ZAI_BUILT_IN_WEB_SEARCH_USD_PER_USE,
    ZAI_CHAT_COMPLETIONS_PATH,
    ZAI_DOCS_PRICING_URL,
    ZAI_OPENAI_BASE_URL,
    ZAI_OPENAPI_URL,
    JsonModelGatewayCatalogStore,
    SqliteModelGatewayCatalogStore,
    createCanonicalModelProjection,
    createCanonicalProviderProjection,
    createAnthropicModelsImporter,
    createCatalogImportRun,
    createCerebrasPublicModelsImporter,
    createChutesModelsImporter,
    createCloudflareWorkersAiCatalogImporter,
    createDefaultModelGatewayCatalogImporters,
    createGeminiModelsImporter,
    createGroqDocsModelsImporter,
    createGroqModelsImporter,
    createHuggingFaceInferenceProvidersImporter,
    createKiloGatewayModelsImporter,
    createKiloGatewayProvidersImporter,
    createMistralModelsImporter,
    createModelMetadataEvidence,
    createModelRouteOption,
    createNvidiaNimModelsImporter,
    createOllamaCatalogImporter,
    createOpenCodeZenDocsImporter,
    createOpenCodeZenModelsImporter,
    createOpenAICompatibleModelsImporter,
    createOpenAIModelsImporter,
    createOpenRouterModelsImporter,
    createZaiModelsImporter,
    createProviderAccountOverlay,
    createProviderCatalogSource,
    createProviderMetadataEvidence,
    createSanitizedRawPayloadRef,
    diffCanonicalModelProjections,
    explainModelGatewayCatalogEntry,
    explainModelGatewayProviderEntry,
    mergeModelMetadataEvidence,
    mergeProviderMetadataEvidence,
    normalizeAccountOverlayControls,
    normalizeCatalogModalities,
    normalizeModelAliases,
    normalizeModelIdentityTraits,
    normalizeModelLifecycle,
    normalizeModelModalities,
    normalizeModelRoutePolicyTraits,
    normalizeModelTokenLimits,
    normalizeOpenAICompatibleModelCapabilities,
    normalizeStoredCatalogSnapshot,
    normalizeUsdPricing,
    mirrorModelGatewayCatalogSnapshotToSqlite,
    parseModelModalityExpression,
    rankCatalogEvidenceConfidence,
    refreshModelGatewayCatalog,
    runCatalogImporters,
    searchModelGatewayCatalogEntries,
    summarizeModelGatewayCatalogSnapshot,
    summarizeCanonicalModelProjectionDiff,
    toOpenAIModelCatalogEntry,
    toOpenAIModelCatalogList,
} from './catalog/index.js';
export {
    MODEL_GATEWAY_SCHEMA_VERSION,
    MODEL_GATEWAY_VERIFICATION_CONFIDENCE,
    buildProviderModelId,
    createModelRecord,
    createProviderRecord,
    normalizeCapabilityProfile,
    normalizeGatewayIdPart,
    normalizeModalities,
    normalizeVerification,
    optionalPositiveInteger,
    optionalString,
} from './contracts/index.js';
export {
    DEFAULT_MODEL_GATEWAY_REGISTRY_PATH,
    JsonModelGatewayRegistryStore,
    ModelGatewayRegistry,
    buildEnvByokModelGatewaySnapshot,
    buildModelGatewayOperatorProjection,
    importConfiguredByokFromEnv,
    normalizeStoredRegistrySnapshot,
    persistEnvByokModelGatewaySnapshot,
} from './registry/index.js';
export {
    DEFAULT_MODEL_GATEWAY_SECRET_ENV_KEYS,
    EnvSecretRegistry,
    createEnvSecretRegistry,
    redactSecretRecord,
    redactSecretText,
} from './secrets/index.js';
export {
    MODEL_GATEWAY_ELIGIBILITY_DISPOSITION,
    MODEL_GATEWAY_ELIGIBILITY_HARD_REASONS,
    MODEL_GATEWAY_ELIGIBILITY_RUN_STATUS,
    MODEL_GATEWAY_ELIGIBILITY_SCHEMA_VERSION,
    MODEL_GATEWAY_ELIGIBILITY_SOFT_REASONS,
    applyModelGatewayEligibilityToSnapshot,
    createModelEligibilityDecision,
    createModelEligibilityRun,
    evaluateModelGatewayCatalogEligibility,
    evaluateModelGatewayEligibility,
    explainModelGatewayEligibilityDecision,
    modelEligibilityDecisionKey,
} from './eligibility/index.js';
export {
    MODEL_GATEWAY_PRE_K_STAGE,
    buildModelGatewayPreKCompatibilityReport,
} from './migration/index.js';
export {
    ANTHROPIC_BASE_URL,
    ANTHROPIC_PROVIDER_ID,
    AnthropicAdapter,
    GEMINI_OPENAI_BASE_URL,
    GEMINI_PROVIDER_ID,
    GeminiAdapter,
    MODEL_GATEWAY_PROVIDER_ENDPOINT_INVENTORY,
    OPENROUTER_BASE_URL,
    OPENROUTER_DEFAULT_HEADERS,
    OPENROUTER_PROVIDER_ID,
    OLLAMA_CLOUD_BASE_URL,
    OLLAMA_LOCAL_BASE_URL,
    OLLAMA_PROVIDER_IDS,
    OPENAI_PROVIDER_FAMILY_SPECS,
    OllamaAdapter,
    OpenAIProviderFamilyAdapter,
    ProviderAdapterRegistry,
    anthropicAdapter,
    createDefaultProviderAdapterRegistry,
    defaultProviderAdapterRegistry,
    geminiAdapter,
    listProviderEndpointInventory,
    OpenAICompatibleAdapter,
    OpenRouterAdapter,
    ollamaAdapter,
    openAICompatibleAdapter,
    openAIProviderFamilyAdapters,
    openRouterAdapter,
    resolveProviderEndpointInventory,
    resolveModelGatewayProviderAdapter,
} from './providers/index.js';
export {
    evaluateGatewayModelHealthRoute,
    isGatewayModelAgentProbeHealthFailed,
    isGatewayModelAgentProbeVerified,
    isGatewayModelChatHealthFailed,
    listModelGatewayTaskProfiles,
    MODEL_GATEWAY_TASK_PROFILES,
    readGatewayModelHealth,
    routeGatewayModels,
    resolveModelGatewayTaskProfile,
    scoreGatewayModelCandidate,
} from './routing/index.js';
export { buildModelGatewayOnListModelsHandler, toCopilotModelInfo, toCopilotModelInfoList } from './session/index.js';
export {
    classifyByokProviderFailure,
    clearByokProviderModelHealth,
    flushByokProviderHealth,
    listByokProviderModelHealth,
    mirrorByokProviderHealthToSqlite,
    readByokProviderHealthState,
    readByokProviderModelHealth,
    recordByokProviderModelAgentProbeFailure,
    recordByokProviderModelAgentProbeSuccess,
    recordByokProviderModelCallFailure,
    recordByokProviderModelCallSuccess,
    recordByokProviderModelProbeResult,
    resetByokProviderHealthForTests,
} from './health/index.js';
export {
    BYOK_AGENT_PROBE_ANSWER,
    BYOK_AGENT_PROBE_QUESTION,
    BYOK_AGENT_PROBE_READ_PATH,
    BYOK_AGENT_PROBE_READ_TOOL,
    BYOK_AGENT_PROBE_TOOL,
    BYOK_VISION_PROBE_DISPLAY_NAME,
    BYOK_VISION_PROBE_MIME_TYPE,
    runConfiguredByokAgentProbe,
    runConfiguredByokChatProbe,
    runConfiguredByokJsonProbe,
    runConfiguredByokStreamingProbe,
    runConfiguredByokVisionProbe,
    recommendCatalogDiffProbes,
} from './probes/index.js';
export {
    MODEL_GATEWAY_CATALOG_CONFLICT_DETECTED,
    MODEL_GATEWAY_CATALOG_IMPORT_COMPLETED,
    MODEL_GATEWAY_CATALOG_IMPORT_STARTED,
    MODEL_GATEWAY_CATALOG_MODEL_ADDED,
    MODEL_GATEWAY_CATALOG_MODEL_CHANGED,
    MODEL_GATEWAY_CATALOG_MODEL_REMOVED,
    MODEL_GATEWAY_ELIGIBILITY_EVALUATED,
    MODEL_GATEWAY_EVENTS,
    MODEL_GATEWAY_MODEL_IMPORTED,
    MODEL_GATEWAY_PROBE_COMPLETED,
    MODEL_GATEWAY_PROVIDER_FAILURE,
    MODEL_GATEWAY_PROVIDER_IMPORTED,
    MODEL_GATEWAY_REGISTRY_SNAPSHOT,
    MODEL_GATEWAY_ROUTE_DECISION,
    buildCatalogConflictDetectedEvents,
    buildCatalogRefreshEventBatch,
    buildCatalogRefreshCompletedEvent,
    buildCatalogRefreshModelEvents,
    buildCatalogRefreshStartedEvent,
    buildEligibilityEvaluatedEvent,
    buildProbeCompletedEvent,
    buildRegistrySnapshotEvent,
    buildRouteDecisionEvent,
    buildRouteDecisionTraceAttributes,
    projectCatalogRefreshCompletedMetrics,
    projectEligibilityEvaluatedMetrics,
    projectProbeCompletedMetrics,
    projectRouteDecisionMetrics,
    projectModelGatewayMetrics,
    listModelGatewayRouteDecisions,
    recordModelGatewayRouteDecision,
    resetModelGatewayRouteDecisionLedgerForTests,
} from './observability/index.js';
