export const AUDIT_EVENT_TYPES = Object.freeze({
    RUN_STARTED: 'run_started',
    RUN_FINISHED: 'run_finished',
    RUN_ABORTED: 'run_aborted',
    RUN_FATAL: 'run_fatal',
    PHASE_STARTED: 'phase_started',
    PHASE_FINISHED: 'phase_finished',
    STEP_STARTED: 'step_started',
    STEP_FINISHED: 'step_finished',
    STEP_PROGRESS: 'step_progress',
    STEP_OUTPUT_TRUNCATED: 'step_output_truncated',
    HEARTBEAT: 'heartbeat',
    WARNING: 'warning',
    ERROR: 'error',
    CONTRACT_LOADED: 'contract_loaded',
    CONTRACT_MATCHED: 'contract_matched',
    CONTRACT_VIOLATED: 'contract_violated',
    CONTRACT_CORRELATED: 'contract_correlated',
    PROPOSAL_GENERATED: 'proposal_generated',
    GATE_DECISION_MADE: 'gate_decision_made',
    RETENTION_PRUNED: 'retention_pruned',
    SECURITY_ANALYSIS_COMPLETED: 'security_analysis_completed',
    PERFORMANCE_ANALYSIS_COMPLETED: 'performance_analysis_completed',
    ARCHITECTURE_ANALYSIS_COMPLETED: 'architecture_analysis_completed',
});

export const AUDIT_PHASES = Object.freeze({
    PREFLIGHT: 'preflight',
    CONTEXT_REFRESH: 'context-refresh',
    COLLECT_QUALITY: 'collect-quality',
    COLLECT_STATIC: 'collect-static',
    COLLECT_RUNTIME: 'collect-runtime',
    COLLECT_TESTS: 'collect-tests',
    COLLECT_CHAOS: 'collect-chaos',
    COLLECT_PERFORMANCE: 'collect-performance',
    COLLECT_ARCHITECTURE: 'collect-architecture',
    NORMALIZE_CORRELATE: 'normalize-correlate',
    TRIAGE_INTELLIGENCE: 'triage-intelligence',
    PUBLISH: 'publish',
});
