#!/usr/bin/env bash
# =============================================================================
# sync-local-auth.sh — Bootstrap local de segredos e autenticação CLI
#
# Propósito:
# - Tornar `.env.local` visível para shells interativos e login shells
# - Persistir autenticação do GitHub CLI (`gh`) em HOME compartilhado
# - Operar em modo fail-safe: nunca deve quebrar lifecycle hooks
#
# Contrato:
# - Sem segredos hardcoded
# - `.env.local` continua sendo a fonte local preferida (gitignored)
# - `remoteEnv` continua válido, mas `.env*.local` sobrescreve chaves duplicadas quando presente
# =============================================================================

set +e
set +u
set +o pipefail 2>/dev/null || true

readonly SCRIPT_NAME="sync-local-auth.sh"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
readonly PROJECT_ROOT
readonly HOME_DIR="${HOME:-/home/node}"
readonly PROFILE_DIR="${XDG_CONFIG_HOME:-${HOME_DIR}/.config}/profile.d"
readonly PROFILE_SNIPPET="${PROFILE_DIR}/20-chatgpt-docker-puppeteer-env.sh"
readonly PROFILE_BLOCK_BEGIN="# >>> chatgpt-docker-puppeteer local env >>>"
readonly PROFILE_BLOCK_END="# <<< chatgpt-docker-puppeteer local env <<<"

log_info() { printf "%s\n" "ℹ️  [${SCRIPT_NAME}] $*"; }
log_warn() { printf "%s\n" "⚠️  [${SCRIPT_NAME}] $*"; }

ensure_profile_hook() {
  mkdir -p "${PROFILE_DIR}" 2>/dev/null || return 1

  cat > "${PROFILE_SNIPPET}" <<EOF
#!/bin/sh
# Generated by ${SCRIPT_NAME}. Safe to overwrite.
if [ -n "\${CHATGPT_DOCKER_PUPPETEER_LOCAL_ENV_LOADED:-}" ]; then
  return 0 2>/dev/null || exit 0
fi
# Shell-local guard only: do not export, so child shells can still load .env.local.
CHATGPT_DOCKER_PUPPETEER_LOCAL_ENV_LOADED=1

if [ -f "${PROJECT_ROOT}/.env.local" ]; then
  set -a
  . "${PROJECT_ROOT}/.env.local"
  set +a
fi
EOF
  chmod 644 "${PROFILE_SNIPPET}" 2>/dev/null || true

  local rc_file
  local block
  block="${PROFILE_BLOCK_BEGIN}
if [ -f \"${PROFILE_SNIPPET}\" ]; then
  . \"${PROFILE_SNIPPET}\"
fi
${PROFILE_BLOCK_END}"

  for rc_file in "${HOME_DIR}/.profile" "${HOME_DIR}/.bashrc"; do
    touch "${rc_file}" 2>/dev/null || continue
    if grep -Fq "${PROFILE_BLOCK_BEGIN}" "${rc_file}" 2>/dev/null; then
      continue
    fi
    printf "\n%s\n" "${block}" >> "${rc_file}" 2>/dev/null || true
  done

  return 0
}

load_local_env_now() {
  if [[ -f "${PROFILE_SNIPPET}" ]]; then
    unset CHATGPT_DOCKER_PUPPETEER_LOCAL_ENV_LOADED 2>/dev/null || true
    # shellcheck disable=SC1090
    . "${PROFILE_SNIPPET}"
  fi
}

sync_gh_auth() {
  local persist_token=""
  local runtime_token=""
  persist_token="${GITHUB_PERSONAL_ACCESS_TOKEN:-}"

  runtime_token="${GH_TOKEN:-}"
  if [[ -z "${runtime_token}" ]]; then
    runtime_token="${GITHUB_TOKEN:-}"
  fi

  if ! command -v gh >/dev/null 2>&1; then
    log_warn "gh não encontrado; bootstrap de GitHub CLI ignorado."
    return 0
  fi

  if [[ -z "${persist_token}" ]]; then
    if [[ -n "${runtime_token}" ]]; then
      log_info "gh usará token de ambiente (GH_TOKEN/GITHUB_TOKEN); sem persistência em ~/.config/gh."
      return 0
    fi
    log_info "Nenhum token GitHub encontrado em GH_TOKEN/GITHUB_TOKEN/GITHUB_PERSONAL_ACCESS_TOKEN."
    return 0
  fi

  if printf "%s" "${persist_token}" \
    | env -u GH_TOKEN -u GITHUB_TOKEN -u GH_ENTERPRISE_TOKEN -u GITHUB_ENTERPRISE_TOKEN \
      gh auth login --hostname github.com --git-protocol https --with-token >/dev/null 2>&1; then
    env -u GH_TOKEN -u GITHUB_TOKEN -u GH_ENTERPRISE_TOKEN -u GITHUB_ENTERPRISE_TOKEN \
      gh auth setup-git >/dev/null 2>&1 || true
    log_info "Autenticação do gh sincronizada em ~/.config/gh."
    return 0
  fi

  if gh auth status --hostname github.com >/dev/null 2>&1; then
    log_info "gh já autenticado; mantendo credenciais atuais."
    return 0
  fi

  log_warn "Falha ao sincronizar gh; verifique escopos do token (repo, read:org, gist)."
  return 0
}

ensure_profile_hook || log_warn "Não foi possível instalar hook de shell para .env.local."
load_local_env_now || true
sync_gh_auth || true

exit 0
