// @ts-check
/**
 * @module copilot/agent/facades
 * @file Barrel canônico das façades públicas do runtime do agent.
 *
 *   `agent/index.js` continua sendo o ponto compatível amplo, mas a lista de façades modernas passa por este arquivo para
 *   facilitar governança de exports e futuras migrações para runtime façade/queries.
 */

export {
    dispatchAgentDialogTurn,
    isAgentDialogLoopPaused,
    pauseAgentDialogLoop,
    readAgentDialogLastPrInfo,
    readAgentDialogPrMetrics,
    recoverAgentDialogInputChannel,
    sendAgentDialogTurn,
    startAgentDialogLoop,
    stopAgentDialogLoopAuthorized,
} from './agent-dialog-runtime.js';
export { readAgentHealthInputSnapshot } from './agent-health-access.js';
export {
    getModel,
    getReasoningEffort,
    listAvailableModels,
    listSdkCatalogModels,
    observeRuntimeModelChange,
    readRuntimeAutoModelPolicy,
    readRuntimeModelSelection,
    readSdkModelMetadata,
    readSdkModelStats,
    setModel,
    setReasoningEffort,
    setRuntimeModel,
    setRuntimeReasoningEffort,
} from './agent-model-config.js';
export { readAgentRuntimeCapabilities } from './agent-runtime-capabilities.js';
export {
    abortRuntimeCurrentMessage,
    answerRuntimePendingQuestion,
    clearRuntimePendingQuestionShadow,
    createRuntimeSnapshot,
    getRuntimeHandoffHistory,
    getRuntimeHandoffManager,
    listRuntimeSnapshots,
    loadRuntimeSnapshot,
    offRuntimeEvent,
    onRuntimeEvent,
    onceRuntimeEvent,
    pauseRuntimeDialogLoop,
    readRuntimeContextFactoryCapabilities,
    readRuntimeControlState,
    readRuntimeGovernanceState,
    readRuntimeInteractionState,
    readRuntimePermissionCapability,
    readRuntimePermissionMode,
    readRuntimePermissionPolicySnapshot,
    readRuntimePrBudgetSnapshot,
    readRuntimeToolRegistry,
    readRuntimeToolRegistryEntries,
    readRuntimeToolSessionContext,
    resumeRuntimeDialogLoop,
    saveRuntimeSnapshot,
    setRuntimeBackgroundCompactionThreshold,
    setRuntimePermissionMode,
    startRuntime,
    steerRuntimeMessage,
} from './agent-runtime-controls.js';
export { readAgentRuntimeEventBridgeSources, wireAgentRuntimeEventBusBridge } from './agent-runtime-event-bridge.js';
export { clearRuntimeSdkSessionOwnership, syncRuntimeSdkSessionOwnership } from './agent-runtime-ownership.js';
export {
    clearAgentRuntimePendingQuestionShadow,
    markAgentRuntimeDialogPausedForRecovery,
    persistAgentRuntimeDialogState,
    persistAgentRuntimeGracefulShutdownState,
    persistAgentRuntimePendingQuestionState,
    persistAgentRuntimePendingTurnState,
    persistAgentRuntimePrConsumptionSnapshot,
    persistAgentRuntimeStatePartial,
    readAgentRuntimeDialogBootstrapState,
    readAgentRuntimeDialogPersistedState,
    readAgentRuntimePersistedStateAsync,
    readAgentRuntimePersistedStateSync,
    readAgentRuntimeSessionId,
    resetAgentRuntimeGracefulShutdownFlag,
    restoreAgentRuntimePersistentBootState,
    saveAgentRuntimeShutdownSnapshot,
    shouldReapAgentRuntimePendingQuestionShadow,
    shouldScheduleAgentRuntimeDialogBootRecovery,
} from './agent-runtime-state.js';
export {
    readAgentRuntimeHealthSnapshot,
    readAgentRuntimeSdkResourceSnapshot,
    readAgentRuntimeStatusSnapshot,
    readAgentRuntimeStatusValue,
} from './agent-runtime-status.js';
export { readAgentRuntimeTodoSummaries } from './agent-runtime-todos.js';
export { readAgentRuntimeToolEntries, readAgentRuntimeTools } from './agent-runtime-tools.js';
export {
    listAgentRuntimeWebhooks,
    registerAgentRuntimeWebhook,
    unregisterAgentRuntimeWebhook,
} from './agent-runtime-webhooks.js';
export {
    canReadAgentSdkSessionMessages,
    onAgentSdkSessionEvent,
    onAllAgentSdkSessionEvents,
    readAgentSdkSessionMessages,
    sendAgentSdkSession,
    sendAgentSdkSessionAndWait,
    waitForAgentSdkEvent,
} from './agent-sdk-runtime.js';
export {
    deleteAgentSdkPlan,
    deleteSdkPlan,
    getSdkSessionMode,
    readAgentSdkPlan,
    readAgentSdkSessionMode,
    readSdkPlan,
    setAgentSdkSessionMode,
    setSdkSessionMode,
    updateAgentSdkPlan,
    updateSdkPlan,
} from './agent-sdk-session.js';
export {
    abortCurrentMessage,
    getSessionMessages,
    performKeepaliveSdkTick,
    pingDialogWatchdog,
    sessionLog,
} from './agent-session-ops.js';
export { listWebhooks, registerWebhook, unregisterWebhook } from './agent-webhook-ops.js';
export { HealthFacade } from './health-facade.js';
export { PermissionToolsFacade } from './permission-tools-facade.js';
export {
    AGENT_SDK_DEFAULT_MODEL,
    attachAgentSdkBootLifecycleBridge,
    checkAgentSdkAuthStatus,
    compactSdkSession,
    confirmSdkSessionUi,
    createAgentSdkClient,
    createAgentSdkSessionByClient,
    createAgentSdkToolsRegistry,
    createSdkWorkspaceFile,
    deleteAgentSdkSessionByClient,
    deleteSdkSession,
    deselectSdkAgent,
    disconnectAgentSdkSession,
    ensureAgentSdkClientStarted,
    execSdkShell,
    formatValidationResult,
    getAgentConfiguredSessionFsHandler,
    getAgentSdkModelStatsTracker,
    getAgentSdkRecoveryPolicy,
    getAgentSdkToolsConfig,
    getCurrentSdkAgent,
    getForegroundSdkSessionId,
    getLastSdkSessionId,
    getPendingSdkElicitation,
    getSdkAuthStatus,
    getSdkHandles,
    getSdkQuota,
    getSdkResourceSnapshot,
    getSdkSessionCapabilities,
    getSdkStatus,
    getSdkUsageMetrics,
    handleSdkPendingCommand,
    handleSdkPendingPermission,
    handleSdkPendingToolCall,
    inputSdkSessionUi,
    isAgentSdkExperimentalEnabled,
    isSdkSessionUiElicitationAvailable,
    killSdkShell,
    listAgentSdkProtectedSessionIdsByClient,
    listAgentSdkSessionsByClient,
    listPendingSdkElicitations,
    listPendingSdkPermissions,
    listSdkAgents,
    listSdkBuiltInTools,
    listSdkModels,
    listSdkSessions,
    listSdkSkills,
    listSdkWorkspaceFiles,
    loadAgentSdkToolsConfigAsync,
    loginSdkMcpOauth,
    pickDefinedAgentSdkOptions,
    pingAgentSdkClient,
    pingSdk,
    raceAgentSdkEvents,
    readAgentConfiguredSessionFsState,
    readAgentSdkModelRegistryEntry,
    readSdkSkillsGovernance,
    readSdkWorkspaceFile,
    reloadSdkAgents,
    requestSdkElicitation,
    resetSdkSessionApprovals,
    resolvePendingSdkElicitation,
    resumeOrCreateAgentSdkSession,
    selectSdkAgent,
    selectSdkSessionUi,
    setForegroundSdkSessionId,
    setSdkDisabledSkills,
    startAgentSdkBootQuotaBridge,
    stopAgentSdkClient,
    validateAgentContracts,
} from './sdk-access.js';
export { SdkQueryFacade } from './sdk-query-facade.js';
export { StateQueryFacade } from './state-query-facade.js';
