#!/usr/bin/env bash
# Open VS Code Ports Panel Automatically
# This script guides the user to add port forwarding

set -euo pipefail

echo "=========================================="
echo "🔧 PORT FORWARDING SETUP GUIDE"
echo "=========================================="
echo ""

# Verificar se Vite está rodando
if ! pgrep -f "vite" > /dev/null; then
    echo "❌ Vite not running. Starting now..."
    cd /workspaces/chatgpt-docker-puppeteer/src/dashboard-ui
    nohup npm run dev > /tmp/vite.log 2>&1 &
    sleep 3
    echo "✅ Vite started"
    echo ""
fi

# Informações visuais
echo "📋 VS Code Port Forwarding Guide"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Step 1: Locate the PORTS Tab"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  In VS Code, look at the BOTTOM PANEL:"
echo ""
echo "  ┌──────────────────────────────────────────────────────┐"
echo "  │                                                      │"
echo "  │  [TERMINAL] [PROBLEMS] [OUTPUT] [DEBUG] [PORTS] ←──  │"
echo "  │                                           ↑          │"
echo "  │                                           └─ Click   │"
echo "  │                                              here    │"
echo "  └──────────────────────────────────────────────────────┘"
echo ""
echo "  If you don't see PORTS tab:"
echo "    • Press: Ctrl + Shift + P"
echo "    • Type: 'Ports: Focus on Ports View'"
echo "    • Press Enter"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Step 2: Add Port 5173"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  In the PORTS tab, you'll see something like:"
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │  PORTS                                [+] [⚙]          │"
echo "  │                                        ↑                │"
echo "  │  Port    Forwarded Address            └─ Click here    │"
echo "  │  ────    ──────────────────                            │"
echo "  │  3008    localhost:3008                                │"
echo "  │  9224    localhost:9224                                │"
echo "  │                                                         │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
echo "  1. Click the [+] button (Forward a Port)"
echo "  2. Type: 5173"
echo "  3. Press ENTER"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Step 3: Verify Port is Forwarded"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  After adding, you should see:"
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │  PORTS                                                  │"
echo "  │                                                         │"
echo "  │  Port    Forwarded Address      Local Address          │"
echo "  │  ────    ──────────────────      ─────────────          │"
echo "  │  3008    localhost:3008          127.0.0.1:3008        │"
echo "  │  5173    localhost:5173          127.0.0.1:5173    ← ✅│"
echo "  │  9224    localhost:9224          127.0.0.1:9224        │"
echo "  │                                                         │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Step 4: Test in Browser"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Open your Windows browser and go to:"
echo ""
echo "    📍 http://localhost:5173/dashboard/"
echo ""
echo "  Expected Result:"
echo "    ✅ Dark theme dashboard appears"
echo "    ✅ Sidebar with menu (Overview, Tasks, etc.)"
echo "    ✅ Console (F12): [vite] connected."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "=========================================="
echo "🧪 TEST FROM WINDOWS (Optional)"
echo "=========================================="
echo ""
echo "Run this in Windows PowerShell to verify:"
echo ""
echo "  cd /path/to/your/project"
printf '%s\n' '  .\scripts\test-dashboard-from-windows.ps1'
echo ""
echo "Or manually test:"
echo "  Test-NetConnection -ComputerName localhost -Port 5173"
echo ""
echo "=========================================="
echo ""
echo "💡 Troubleshooting:"
echo ""
echo "  ❌ Port still not accessible?"
echo "     → Reload VS Code (Ctrl+Shift+P → 'Reload Window')"
echo "     → Check Docker Desktop is running"
echo "     → Check Windows Firewall"
echo ""
echo "  ❌ Port shows in PORTS but browser fails?"
echo "     → Clear browser cache (Ctrl+Shift+Delete)"
echo "     → Try different browser (Firefox, Edge)"
echo "     → Check browser console (F12) for errors"
echo ""
echo "=========================================="

exit 0
